# Generated by Django 4.1.4 on 2022-12-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
